eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: '8888'
spring:
  application:
    name: gateway-service-zuul
zuul:
  routes:
    api-a:
      path: /producer-01/**
      service-id: spring-cloud-producer-01
    pai-b:
      path: /producer-02/**
      service-id: spring-cloud-producer-02
    